#!/bin/bash
typeset _VERSION=1.0
#    Prints out the active branch's name
#    Copyright (C) 2015 Shawn Dady https://github.com/SDady/git_scripts
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    This is an example of how you could use this in a prompt:
#
#    	PS1='\[\e[0;32m\]\u@\h:$(cm-branch-name):\W>\[\e[0m\]'
#
#########################################

git rev-parse --is-inside-work-tree >/dev/null 2>&1

typeset isGit=$?
if [ "$isGit" == "0" ]; then
	typeset name=$(git rev-parse --abbrev-ref HEAD)
	echo $name
else
	echo ""
fi

