#!/bin/bash
typeset _VERSION=1.0
#    Sets the git config file the way we like it.
#
#    Copyright (C) 2015 Shawn Dady https://github.com/SDady/git_scripts
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

function usage
{
	cat <<-HELP
	Usage: ${ScriptName} [options]
	options
		-h 	show help
		-u	sets user name <required>
		-e	sets user email <required>
	
	Initialize the .gitconfig if needed. 
	HELP
	exit ${ErrBad}
}

trap '>&2 echo ****break**** && exit 1;' HUP INT QUIT TERM

#############################
#	vars
#############################
email=
username=

#############################
#	main
#############################

while [[ -n ${1} ]];
do
	case ${1} in
	-h*|-\?)	#help
		usage;
		;;
	-u)		#user name
		shift
		username=${1}
		;;
	-e)		#user email
		shift	
		email=${1}
		
		;;
	
	*)
		usage;
	esac
	shift;
done

echo "configuring .gitconfig file..."

git config --global user.name ${username:? "-u <username> Required"}
git config --global user.email ${email:? "-e <email> Required"}
git config --global push.default simple
git config --global diff.tool meld
git config --global merge.tool meld
echo "Done."
exit 0
