#!/bin/bash
typeset _VERSION=1.0
#    Used to show files that changed.
#
#    Copyright (C) 2015 Shawn Dady https://github.com/SDady/git_scripts
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

function usage
{
	cat <<-HELP
	Usage: ${ScriptName} [options]
	Valid v${_VERSION} options:
		-h		display help
		-s		short view

	Used to show what has changed and log of commits.
	HELP
	exit ${ErrBad}
}

trap '>&2 echo ****break**** && exit 1;' HUP INT QUIT TERM

#process command-line parameters
#
while [[ -n ${1} ]]
do
	case ${1} in
	-h*|-\?)	#help
		usage
		;;
	*)		#default
		;;
	esac
	shift
done

localPath=`git rev-parse --show-toplevel`
echo "Local repo is $localPath"
if [ $? -ne 0 ]; then
	echo "Not in a git repo."
	exit 1;
fi

cd $localPath
git status -u --porcelain -z | sed -e 's/\x00/\n/g' |
	while read line
	do
		modifed=$(echo $line | awk '{print $1;}')
		file=$(echo $line | awk '{print $2;}')
		echo "$line"	
		if [[ "${modifed:0:1}" == "M" || "${modifed:0:1}" == "A" ]]; then
			`git difftool -y $file`
			#TODO ask the user if they want to skip, add, or reset file
		fi
		#todo ask to add, reset, continue, or exit 
	done
	

