#!/bin/bash
#Default locations
#
#  
#
# Revision History
#	0.1
#
#
#
#
#
#
#
#
#
#
#
#

#########################################
#

usave()
{
	cat <<-HELP
	Usage: ${ScriptName}
	options
		-h 	show help
	src	The source location of the repo e.g. /repos/<project>
	dest	The local working directory. Usually in ~/projects/<project>
	
	This script is used to copy the cm file to /usr/bin/.
	HELP
}
cp cm-* /usr/bin/
